### ISSUE TITLE
Error running titantuner

### ISSUE THREAD

**Issue by Francesco-Uboldi** [metno/titantuner#2]
I installed titantuner with pip3. I create some csv files like this 
`lon;lat;elev;value`
`1.103056;46.19389;189;26.300001`
`11.48;46.284443;840;22.300001`
`11.666667;46.393333;1206;18.1`
`10.913611;46.349167;684;22`
and put them in a directory `20230915/`
Then I issued:
`titantuner -d 20230915`
This in fact opens a browser window, but it says "500: Internal Server Error"
In the terminal windows it says various things, see them here: [error.txt](https://github.com/metno/titantuner/files/13546599/error.txt)
Among the various information I found this one:
`ValueError: zero-size array to reduction operation minimum which has no identity`
I think that this may depend on some package (version?)  on which titantuner depends. 
Do you have any ideas?
Thank you
Francesco Uboldi

**Comment by cristianlussana** [comment]
Hi Francesco,
talking with my colleagues, they are wondering whether you have some other files in the directory 20230915, or some corrupted files, because from the output seems like you are trying to read a "bad" file.
Cristian

**Comment by Francesco-Uboldi** [comment]
No.
I put in the directory `./test/` only  the file `t2m_202309151300.csv` (the same file  I sent yesterday to Cristian who was able to use it with titantuner, I attach it). Then I run
`titantuner -d test`
A window is opened in the browser, with the "map" portion blank (the portion with commands buttons etc appears), I attach the window image too
[t2m_202309151300.csv](https://github.com/metno/titantuner/files/13582116/t2m_202309151300.csv)
![Schermata a 2023-12-06 12-38-28](https://github.com/metno/titantuner/assets/152395595/2da92bd7-f2c9-4493-9f99-e1ad0856af6f)
.
When I interrupt with  ^C, this is what I get:

```
$ titantuner -d test
titanlib version: 0.3.3
----
Opening Bokeh application on http://localhost:8081/
Opening test/t2m_202309151300.csv. Variable rr.
404 GET /favicon.ico (127.0.0.1) 1.15ms
^CTraceback (most recent call last):
  File "/usr/local/bin/titantuner", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/titantuner/__init__.py", line 17, in main
    titantuner.__main__.main()
  File "/usr/local/lib/python3.10/dist-packages/titantuner/__main__.py", line 21, in main
    run(**vars(args))
  File "/usr/local/lib/python3.10/dist-packages/titantuner/__main__.py", line 35, in run
    server.io_loop.start()
  File "/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

```

**Comment by Francesco-Uboldi** [comment]
No , I don't think so. Please see my comment on the issue on the website

Il giorno mar 5 dic 2023 alle ore 13:05 Thomas Nipen <
***@***.***> ha scritto:

**Comment by cristianlussana** [comment]
Hi,
when the window is open on your browser, have you tried to click on the "Update" button. What happens? Does it crash?
Cr

**Comment by Francesco-Uboldi** [comment]
No! With the update button it seems to work!
OK, I guess there still is some work to do on the window size (many
commands, including the "update" button below were off screen) and on
window resize, so I dont'complain about that!
Thank you, I will post another comment on github etc
Francesco

Il giorno mer 6 dic 2023 alle ore 12:52 Cristian Lussana <
***@***.***> ha scritto:

**Comment by Francesco-Uboldi** [comment]
... and probably a clean way to close everything will be needed. But for
the moment it seems to work. After "updating".

Il giorno mer 6 dic 2023 alle ore 13:48 Francesco Uboldi ***@***.***>
ha scritto:
